### ISSUE TITLE
UglifyJS (transitive) dependency stopper

### ISSUE THREAD

**Issue by dhartford** [theTechie/react-component-preview#1]
Hi Team,
Although this is deep in the dependency tree, it is still a showstopper for people that want to evaluate/use react-component-preview 2.0.0:

`npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.`

May just require updating the webpack versions?

**Comment by theTechie** [comment]
@dhartford - it's been a while i wrote this. I will look into this.

**Comment by theTechie** [comment]
@dhartford - i have updated almost all the libraries to latest versions along with yarn.

It should work without any problems now. Could you have a look and let me know if you are still facing any issues ?

NOTE: _I haven't deployed this to apm yet; i will need some more time to do this. For now, you can refer to the updated docs to see how to run it manually_

**Comment by dhartford** [comment]
(moving prior comment to ticket #2 )

The issue related to UglifyJS, and in fact everything related to updated webpack, are working on my system as well using the github react-component-preview 3.0.0 npm install / apm link approach.
