### ISSUE TITLE
Test with create-react-app boilerplate kit from Facebook

### ISSUE THREAD

**Issue by dhartford** [theTechie/react-component-preview#2]
The create-react-app boilerplate kit doesn't work well with the previewer at the moment.

On my windows 7/Atom 1.18 without any other custom packages, getting a stop on react-component-preview.js 115 (startDevServer() ) -> proc exit: 3221226519

The issue above is because the App.js file was not compiling with server.js, but the issue got swallowed up. Should evaluate exposing compile issues.  The actual issue is lack of support for the create-react-app style of app.js (inline html JSX-style)

----

how to recreate:
#install create-react-app globally
npm install -g create-react-app
#go to per-project folder to initialize the boilerplate/scripts
create-react-app hello-world
#to find the version of create-react-app in use, example version 1.3.3, manually review tree
npm list -g
#alternatively, if on a linux-based system: npm list -g | grep create-react-app
#use atom.io with react-component-preview on the default src/App.js

**Comment by theTechie** [comment]
The config we have for the previewer does support JSX-style; probably some corner case.

I will have a look at it. Thanks for the steps to recreate 👍

**Comment by theTechie** [comment]
@dhartford - looks like it should work if you run `npm run eject` command from the project directory (created by create-react-app).

As-is, `react-component-preview` relies on some config in the target project. `create-react-app` hides all the configs until we manually eject.

Could you please try if this works for you?

_PS: i believe the svg file won't be loaded as per the current config. you will have to comment the svg part to make it work._

> I will probably make an option to specify the webpack config in the plugin settings so that this plugin works with all kinds of projects (without much configuration required at the plugin side)

**Comment by theTechie** [comment]
@dhartford - does this work for you ?

**Comment by dhartford** [comment]
Confirmed that did the trick (including the reference to comment out the SVG file and the default {logo} reference).  Hot-update works fine as long as no compile issue (compile issue requires restarting the previewer) but as far as working with create-react-app that was the trick:

`npm run eject`
